# [build]
# target = ["x86_64-pc-windows-gnu", "x86_64-unknown-linux-gnu"] # , "x86_64-apple-darwin", "aarch64-apple-darwin"
[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"

# [target.x86_64-pc-windows-gnu]
# linker = "x86_64-w64-mingw32-ld"
# rustflags = ["-C", "link-arg=-fuse-ld=lld"]
